### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-nikitin#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
9) Поясніть, будь ласка, в чому полягає процес двох факторної аутентифікації 
(two-factor authentication) під час використання протокола SSH 
як мережевого протокола рівня застосунків.

**Comment by 44Nikita44** [comment]
SSH - мережевий протокол встановлення безпечного з’єднання між клієнтом та сервером через підтвердження справжньості програми-клієнта з використанням класу процедур аутентифікації «те, що маю». Даний протокол використовує два ключи: відкритий ключ та закритий ключ. Отож при використанні SSH-протоколу, потребується порівняння відкритого ключа із закритим і у разі успішної перевірки надається доступ. У процесі двохфакторної автентифікації SSH виступає як один із двох факторів автентифікації, разом, наприклад, із стандартним уведенням паролю, що робить даний протокол корисним у якості підвищення безпеки роботи із даними

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
